In [3]:
import torch
import numpy as np
import pickle as pkl

In [4]:
with open("jarvis__dft_3d_2021/all/raw/raw_data.pkl", "rb") as f:
    data = pkl.load(f)

In [3]:
data[0].keys()

dict_keys(['structure', 'material_id', 'formation_energy', 'total_energy', 'opt_bandgap'])

In [18]:
torch.tensor(data[0]["structure"].get_neighbor_list(5)[:2], dtype=torch.long)
# torch.tensor([src, dst], dtype=torch.long)
# src

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6,
         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
        [3, 3, 5, 5, 0, 2, 

In [5]:
data[0]["structure"].atomic_numbers

(22, 22, 29, 29, 14, 14, 33, 33)

In [6]:
len(data)

55723

In [7]:
data[0]["structure"].cart_coords

array([[2.67519992, 2.67519992, 7.37609819],
       [0.89173331, 0.89173331, 2.02097727],
       [0.89173331, 2.67519992, 4.69853773],
       [2.67519992, 0.89173331, 4.69853773],
       [0.89173331, 2.67519992, 0.        ],
       [2.67519992, 0.89173331, 0.        ],
       [2.67519992, 2.67519992, 2.88947816],
       [0.89173331, 0.89173331, 6.50759729]])

In [8]:
with open("jarvis__dft_3d_2021-ehull/all/raw/raw_data.pkl", "rb") as f:
    data = pkl.load(f)

In [9]:
len(data)

55371

In [10]:
data[0].keys()

dict_keys(['structure', 'material_id', 'ehull'])

In [2]:
import pickle as pkl
with open("jarvis__dft_3d_2021-mbj_bandgap/all/raw/raw_data.pkl", "rb") as f:
    data = pkl.load(f)

In [4]:
data[0]["structure"].lattice.matrix

array([[ 1.67774838e+00, -2.90594524e+00, -1.10000000e-15],
       [ 1.67774838e+00,  2.90594524e+00, -7.00000000e-16],
       [-6.50000000e-15, -8.00000000e-16,  6.22080547e+00]])

In [117]:
[data[i]["mbj_bandgap"] for i in range(15)]

[0.0,
 0.0,
 0.0,
 2.276,
 0.256,
 0.959,
 5.672,
 0.0,
 0.0,
 0.0,
 0.0,
 8.382,
 0.0,
 0.0,
 0.0]

In [12]:
len(data)

18172

In [13]:
data[0].keys()

dict_keys(['structure', 'material_id', 'mbj_bandgap'])

In [14]:
path = "jarvis__megnet/all/raw/raw_data.pkl"
with open(path, "rb") as f:
    data = pkl.load(f)


In [15]:
len(data)

69239

In [16]:
data[0].keys()

dict_keys(['material_id', 'bandgap', 'e_form', 'structure'])

In [17]:
with open("jarvis__megnet-bulk/test/raw/raw_data.pkl", "rb") as f:
    data1 = pkl.load(f)
with open("jarvis__megnet-bulk/train/raw/raw_data.pkl", "rb") as f:
    data2 = pkl.load(f)
with open("jarvis__megnet-bulk/val/raw/raw_data.pkl", "rb") as f:
    data3 = pkl.load(f)

In [18]:
len(data1), len(data2), len(data3)

(393, 4664, 393)

In [19]:
data1[0].keys()

dict_keys(['material_id', 'bulk_modulus', 'structure'])

In [20]:
data = data1 + data2 + data3
len(data)

5450

In [21]:
data[0].keys()

dict_keys(['material_id', 'bulk_modulus', 'structure'])

In [22]:
import os
os.makedirs("jarvis__megnet-shear/all/raw", exist_ok=True)

In [23]:
# write data
with open("jarvis__megnet-shear/all/raw/raw_data.pkl", "wb") as f:
    pkl.dump(data, f)

In [24]:
with open("jarvis__megnet-shear/all/raw/raw_data.pkl", "rb") as f:
    data = pkl.load(f)
len(data)

5450

In [25]:
with open("jarvis__megnet-shear/test/raw/raw_data.pkl", "rb") as f:
    data1 = pkl.load(f)
with open("jarvis__megnet-shear/train/raw/raw_data.pkl", "rb") as f:
    data2 = pkl.load(f)
with open("jarvis__megnet-shear/val/raw/raw_data.pkl", "rb") as f:
    data3 = pkl.load(f)

In [26]:
data = data1 + data2 + data3
len(data)

5449

In [27]:
data[0].keys()

dict_keys(['material_id', 'shear_modulus', 'structure'])

In [28]:
os.makedirs("jarvis__megnet-shear/all/raw", exist_ok=True)
with open("jarvis__megnet-shear/all/raw/raw_data.pkl", "wb") as f:
    pkl.dump(data, f)

In [29]:
import pickle as pkl
with open("jarvis_dft_dielectric.pkl", "rb") as f:
    data = pkl.load(f)

C:\Users\asus\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\asus\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (


In [30]:
len(data)

4645

In [31]:
for i in range(20):
    print(data.iloc[i]["dielectric"])

[[11.709474, 0.0, 0.0], [0.0, 11.709474, 0.0], [0.0, 0.0, 8.155179]]
[[5.636145, 0.0, 0.0], [0.0, 5.636147, -0.0], [0.0, -0.0, 4.285379]]
[[4.280192, 1e-06, 0.0], [-1e-06, 4.280193, -0.0], [-0.0, 0.0, 3.885594]]
[[14.47269, -0.0, 0.0], [-0.0, 14.472695, 0.0], [0.0, 0.0, 2.975802]]
[[9.122138, 0.0, -0.0], [0.0, 9.122138, 0.0], [0.0, 0.0, 8.287219]]
[[3.037837, 0.0, 0.0], [0.0, 3.037837, 0.0], [0.0, 0.0, 2.887589]]
[[2.275035, 0.0, 0.0], [0.0, 2.273063, 0.0], [0.0, 0.0, 2.256214]]
[[5.103334, 0.0, 0.0], [0.0, 5.103335, 0.0], [0.0, 0.0, 5.451195]]
[[3.839057, 0.0, -0.0], [-0.0, 3.839057, -0.0], [0.0, -0.0, 3.839057]]
[[3.271077, 0.0, 0.0], [0.0, 3.271077, -0.0], [0.0, 0.0, 5.200021]]
[[2.603417, 0.0, 0.0], [0.0, 2.603417, -0.0], [0.0, -0.0, 2.561821]]
[[2.459263, 0.0, 0.0], [0.0, 2.459263, -0.0], [0.0, 0.0, 2.489952]]
[[4.186096, 0.053826, -0.04427], [0.053815, 4.105669, -0.194675], [-0.044278, -0.194738, 4.94605]]
[[3.792746, 0.0, -0.0], [0.0, 3.792746, 0.0], [0.0, 0.0, 3.621261]]
[[4.08

In [32]:
with open("jarvis_dft_dielectric_ionic.pkl", "rb") as f:
    data = pkl.load(f)

In [33]:
data.iloc[0]

atom_nums                              (68, 68, 30, 30, 33, 33, 8, 8)
atom_pos            [[0.0, 1.961983, 1.0688937169700001], [1.96198...
lattice_mat         [[3.923966, 0.0, 0.0], [0.0, 3.923966, 0.0], [...
dielectric_ionic    [[19.87658, 0.0, 0.0], [0.0, 19.876578, 0.0], ...
JARVIS_ID                                                 JVASP-37833
Name: 0, dtype: object

In [34]:
import pickle as pkl
# jarvis_dft_piezoelectric_e_Angst.pkl
with open("jarvis_dft_piezoelectric_e_Angst.pkl", "rb") as f:
    data = pkl.load(f)


In [35]:
data.iloc[0]["piezoelectric_e_Angst"]
# Output:
[[0.01316, -0.00721, -0.00595, 0.0, 0.0, 0.0],
 [-0.00721, 0.01316, -0.00596, 0.0, 0.0, 0.0],
 [-0.00166, -0.00166, 0.00443, 0.0, 0.0, 0.0]]

[[0.01316, -0.00721, -0.00595, 0.0, 0.0, 0.0],
 [-0.00721, 0.01316, -0.00596, 0.0, 0.0, 0.0],
 [-0.00166, -0.00166, 0.00443, 0.0, 0.0, 0.0]]

In [36]:
import pickle as pkl

with open("jarvis_dft_elastic_sym_kbar.pkl", "rb") as f:
    data = pkl.load(f)

In [37]:
data.iloc[0]["elastic_sym_kbar"]

[[2308.9237, 1267.3252, 1031.8209, -0.0, -0.0, 0.0],
 [1267.3252, 2308.9234, 1031.8208, -0.0, -0.0, 0.0],
 [1031.8209, 1031.8208, 2740.44, -0.0, 0.0, 0.0],
 [-0.0, 0.0, -0.0, 520.7992, 0.0, 0.0],
 [0.0, -0.0, 0.0, -0.0, 627.2264, 0.0],
 [-0.0, 0.0, 0.0, -0.0, 0.0, 627.2264]]

In [38]:
! pwd

/e/课业/课题组/high_order/data


In [45]:
import sqlite3
import numpy as np

conn = sqlite3.connect("materials_project_full.db")
cursor = conn.cursor()

# Print all the tables
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())


[('systems',), ('sqlite_sequence',), ('species',), ('keys',), ('text_key_values',), ('number_key_values',), ('information',)]


In [105]:
# Look into the table 'systems'
cursor.execute("SELECT * FROM systems")
# for i in range(len(cursor.description)):
#     print(cursor.description[i][0], type(cursor.fetchone()[i]))
# np.frombuffer(cursor.fetchone()[6])
for i in range(10):
    print(cursor.fetchone()[0])

1
2
3
4
5
6
7
8
9
10


Hey, all the properties in mp have not been downloaded yet.

The only thing we have is the structure data.

In [44]:
from dataloaders.materials_db_reader import MaterialsProjectDatabase

In [73]:
np.frombuffer(cursor.fetchone()[5])

array([1.08221785e-312, 1.08221785e-312])

In [103]:
data1 = cursor.fetchone()

In [104]:
np.frombuffer(data1[5])

array([3.18299369e-313, 3.18299369e-313, 3.18299369e-313, 3.18299369e-313])

In [109]:
cursor.description

(('id', None, None, None, None, None, None),
 ('unique_id', None, None, None, None, None, None),
 ('ctime', None, None, None, None, None, None),
 ('mtime', None, None, None, None, None, None),
 ('username', None, None, None, None, None, None),
 ('numbers', None, None, None, None, None, None),
 ('positions', None, None, None, None, None, None),
 ('cell', None, None, None, None, None, None),
 ('pbc', None, None, None, None, None, None),
 ('initial_magmoms', None, None, None, None, None, None),
 ('initial_charges', None, None, None, None, None, None),
 ('masses', None, None, None, None, None, None),
 ('tags', None, None, None, None, None, None),
 ('momenta', None, None, None, None, None, None),
 ('constraints', None, None, None, None, None, None),
 ('calculator', None, None, None, None, None, None),
 ('calculator_parameters', None, None, None, None, None, None),
 ('energy', None, None, None, None, None, None),
 ('free_energy', None, None, None, None, None, None),
 ('forces', None, None, N

In [113]:
for i in data1:
    print(i)

12
a37e570174da7527ba5144eb33789455
25.252083577357237
25.252083577357237
mingkang_nt
b'\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00\x0f\x00\x00\x00'
b'\x8f\x7f\xfd\xd5\xbbs\xf6?\x8a\xd03)\x95I\xf0?<T%\xb2\xde\x00\xf2?\x8b\xc7\xd3\x07C\xc5\x10@itr\x94-\xe8\x15@M~\xaf\xfe8)\x18@\x18\xb6\x17x1\x92\t@?ZS\xcd\xf0\x9c\xfd?%\xee\x151\x1fc\x00@\xc7\x98\x8e\x8222\x03@\xfc\x91j\xabV\x93\x12@J\xdc\xad\x12\xe1w\x14@,\xa6\xaf3[\xc4\xf6?6m\xb7\xac\x18\xc7\x08@\xc1\x12\x9ag\xb2\xa5\xfc?\x0c\x1b+h$\xb7\x10@\x17\x90\xef\xe1\x14\x0c\x14@\xf9%,\xcd\xfaA\x0f@\xe5=g0\x1b\xb1\x10@\xdec\xc7\x10\r.\x0b@\xacNR\x11\x04\x80\x15@\x8f1\xa0T6\xac\xf6?\xcfa?\xf3\xf7\xb9\xf7?\xbd\x80E\x89\xe6\x10\n@'
b'\x8c8S\xd7\x90R\x16@\x87\x1e)\t&\x8aR\xbf\x01T/\xc7D\xad\x95?\x8c4\n\xac\x90\xb0\x93?\x939T[\x03\xb2\x19@T\xbc\x99\xea,\xe7\xe5?\xa9Em\xb0\xaa=p\xbf~b\xf0r\tn\xb2?}l\x1e\xc9\xdd\xd6\x19@'
7
b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

In [6]:
import pickle as pkl
import os

with open("jarvis__megnet-bulk\\test\\raw\\raw_data.pkl", "rb") as f:
    data_test = pkl.load(f)
with open("jarvis__megnet-bulk\\train\\raw\\raw_data.pkl", "rb") as f:
    data_train = pkl.load(f)
with open("jarvis__megnet-bulk\\val\\raw\\raw_data.pkl", "rb") as f:
    data_val = pkl.load(f)
data_all = data_test + data_train + data_val
os.makedirs("jarvis__megnet-bulk\\all\\raw", exist_ok=True)
with open("jarvis__megnet-bulk\\all\\raw\\raw_data.pkl", "wb") as f:
    pkl.dump(data_all, f)
len(data_test), len(data_train), len(data_val), len(data_all)


(393, 4664, 393, 5450)

In [8]:
with open("jarvis__megnet-shear\\all\\raw\\raw_data.pkl", "rb") as f:
    data = pkl.load(f)

len(data)

5449

In [14]:
import pickle as pkl
property_name = "elastic_total_kbar"

with open(f"processed_jarvis_{property_name}.pkl", "rb") as f:
    data = pkl.load(f)

for i in range(len(data)):
    if data[i][property_name] is None:
        print(i) # 6294
print(len(data))

14499


In [13]:
data = data[:6294] + data[6295:]
with open("processed_jarvis_elastic_total_kbar.pkl", "wb") as f:
    pkl.dump(data, f)
print("Done")

Done


In [ ]:
import torch

neighbor_list = torch.load("neighbor_list/mp_neighbor_list_cutoff_5.00.pt")
neighbor_list[0]

: 

In [ ]:
from pymatgen.core import Lattice, Structure

def jarvis_atoms_to_pymatgen(atoms: dict) -> Structure:
    lattice_mat = atoms["lattice_mat"]          # 3x3 lattice matrix
    coords = atoms["coords"]                    # fractional or cartesian
    elements = atoms["elements"]                # species list
    is_cartesian = bool(atoms.get("cartesian", False))

    if len(coords) != len(elements):
        raise ValueError("coords and elements length mismatch")

    lattice = Lattice(lattice_mat)
    structure = Structure(
        lattice=lattice,
        species=elements,
        coords=coords,
        coords_are_cartesian=is_cartesian,
    )
    return structure

In [ ]:
import json

with open("carbon_24.json", "r") as f:
    data_c = json.load(f)

length = len(data_c)
print("length:", length)
from tqdm import tqdm
import pickle as pkl

print("Start processing...")
for i in tqdm(range(length)):
    row = data_c[i]
    structure = jarvis_atoms_to_pymatgen(row["atoms"])
    row["structure"] = structure

print("Processing completed. Saving to file...")
with open("carbon_24_structures.pkl", "wb") as f:
    pkl.dump(data_c, f)

print("Done.")